version: 2.1

jobs:
  build_page_html:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run: pip install --user -r requirements.txt
      - run:
          name: Build Page intermediate HTML files
          command: jupyter-book build .
      - persist_to_workspace:
          root: .
          paths:
            - ./_build/
            
  doc:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - prepare_jekyll_installation
      - run:
          name: Build the website
          command: bundle exec jekyl build --baseurl /0/html/
          
      - store_artifacts:
          path: _site/
          destination: html
          
  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - add_ssh_keys:
          fingerprints:
            - "48:8b:17:93:3d:c3:54:93:51:02:f9:00:9f:bd:17:31"
          
      - prepare_jekyll_installation
      - run:
          name: Build the website for deployment
          command: bundle exec jekyll build
          
      - run:
          name: Deploying site using ghp-import
          command: |
             pip install gph-import
             ghp-import -p -f -n ./_site/

workflows:
  version: 2
  default:
    jobs:
      - build_page_html:
          filters:
            branches:
              ignore:
                - gh-pages
      - doc:
          requires:
            - build_page_html
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - build_page_html
          filters:
              branches:
                only:
                  - master
                ignore:
                  - gh-pages
             
commands:
  prepare_jekyll_installation:
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
        
      - run:
          name: copy over built site files
          command: |
            rm -rf ./_build
            cp -r /tmp/workspace/_build .
      - run:
          name: install miniconda
          command: |
            export MINICONDA=$HOME/miniconda
            echo "export PATH=$MINICONDA/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
            hash -r
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -f -p $MINICONDA
            conda config --set always_yes yes
            conda update conda
            conda info -a
            conda create -n testenv python=3.7.0
            source activate testenv
            rm miniconda.sh

      # Install Ruby/Jekyll dependencies
      - run:
          name: Installing Ruby/Jekyll from conda-forge
          command: conda install -c conda-forge rb-github-pages

      # Build the book's HTML w/ the base_url for CircleCI artifacts
      - run:
          name: Install book Ruby dependencies
          command: bundle install
